insert into secao_produto (descricao,comercializavel)values('CONDIMENTOS','1');
insert into secao_produto (descricao,comercializavel)values('EMBALAGEM','0');
insert into secao_produto (descricao,comercializavel)values('MATERIA PRIMA','1');
insert into secao_produto (descricao,comercializavel)values('PRODUTO ACABADO','0');
insert into secao_produto (descricao,comercializavel)values('SERVICO','1');
insert into secao_produto (descricao,comercializavel)values('SUB PRODUTO','1');
insert into secao_produto (descricao,comercializavel)values('LOGISTICA','0');
insert into secao_produto (descricao,comercializavel)values('MANUTENÇÃO','0');
insert into secao_produto (descricao,comercializavel)values('REFEITORIO','0');
insert into secao_produto (descricao,comercializavel)values('FARDAMENTOS E ACESSORIOS','0');
insert into secao_produto (descricao,comercializavel)values('MATERIAIS DE USO E CONSUMO','0');
insert into secao_produto (descricao,comercializavel)values('IMOBILIZADO','0');
insert into secao_produto (descricao,comercializavel)values('GRAXARIA','1');
insert into secao_produto (descricao,comercializavel)values('DEPARTAMENTO PESSOAL','0');
insert into secao_produto (descricao,comercializavel)values('HIGIENIZAÇÃO','0');
insert into secao_produto (descricao,comercializavel)values('MATERIAL DE EXPEDIENTE','0');